export const jobs = [
  {
    id: '1',
    title: 'Senior Frontend Developer',
    company: 'TechCorp Inc.',
    description:
      'We are looking for an experienced frontend developer to join our growing team. You will be responsible for building modern web applications using React and TypeScript.',
    fullDescription:
      'We are seeking a talented Senior Frontend Developer to join our dynamic team at TechCorp Inc. In this role, you will be responsible for developing and maintaining high-quality web applications using modern frontend technologies. You will work closely with our design and backend teams to create exceptional user experiences that drive our business forward. The ideal candidate has a strong background in React, TypeScript, and modern frontend development practices.',
    location: 'San Francisco, CA',
    type: 'Full-Time',
    posted: '2 days ago',
    requirements: [
      '5+ years of experience in frontend development',
      'Strong proficiency in React and TypeScript',
      'Experience with modern CSS frameworks (Tailwind CSS preferred)',
      'Knowledge of state management libraries (Redux, Zustand)',
      'Familiarity with testing frameworks (Jest, React Testing Library)',
      'Experience with version control systems (Git)',
      'Strong problem-solving and communication skills',
    ],
    benefits: [
      'Competitive salary and equity package',
      'Comprehensive health, dental, and vision insurance',
      'Flexible work arrangements and remote options',
      'Professional development budget',
      'Unlimited PTO policy',
      'Modern office space with free meals and snacks',
    ],
  },
  {
    id: '2',
    title: 'Product Designer',
    company: 'Design Studio',
    description:
      'Join our creative team as a Product Designer. You will design user interfaces and experiences for web and mobile applications.',
    fullDescription:
      'Design Studio is looking for a creative and detail-oriented Product Designer to join our team. You will be responsible for designing intuitive and engaging user interfaces for both web and mobile applications. Working closely with product managers and developers, you will help shape the user experience of our products from concept to launch. We value creativity, attention to detail, and a user-centered design approach.',
    location: 'New York, NY',
    type: 'Full-Time',
    posted: '1 week ago',
    requirements: [
      '3+ years of experience in product design',
      'Proficiency in design tools (Figma, Sketch, Adobe Creative Suite)',
      'Strong understanding of UX/UI principles',
      'Experience with design systems and component libraries',
      'Knowledge of prototyping and user testing',
      'Portfolio demonstrating design process and outcomes',
      'Excellent communication and collaboration skills',
    ],
    benefits: [
      'Competitive salary with performance bonuses',
      'Health and wellness benefits',
      'Flexible working hours',
      'Creative workspace with latest design tools',
      'Conference and workshop attendance budget',
      'Team building activities and company retreats',
    ],
  },
  {
    id: '3',
    title: 'Backend Engineer',
    company: 'DataFlow Systems',
    description:
      'We need a skilled backend engineer to help build scalable APIs and microservices. Experience with Node.js and cloud platforms required.',
    fullDescription:
      'DataFlow Systems is seeking a talented Backend Engineer to join our engineering team. You will be responsible for designing, developing, and maintaining scalable backend systems and APIs that power our data processing platform. The role involves working with microservices architecture, cloud technologies, and ensuring high performance and reliability of our systems. You will collaborate with frontend developers, data scientists, and DevOps engineers to deliver robust solutions.',
    location: 'Remote',
    type: 'Full-Time',
    posted: '3 days ago',
    requirements: [
      '4+ years of backend development experience',
      'Strong proficiency in Node.js and JavaScript/TypeScript',
      'Experience with RESTful APIs and GraphQL',
      'Knowledge of database systems (PostgreSQL, MongoDB)',
      'Familiarity with cloud platforms (AWS, GCP, Azure)',
      'Understanding of microservices architecture',
      'Experience with containerization (Docker, Kubernetes)',
    ],
    benefits: [
      'Fully remote work environment',
      'Competitive salary and stock options',
      'Comprehensive health benefits',
      'Home office setup allowance',
      'Learning and development budget',
      'Annual company retreat',
      'Flexible vacation policy',
    ],
  },
  {
    id: '4',
    title: 'Marketing Specialist',
    company: 'GrowthLab',
    description:
      'Looking for a creative marketing specialist to help drive our digital marketing campaigns and brand awareness initiatives.',
    fullDescription:
      'GrowthLab is seeking an enthusiastic Marketing Specialist to join our marketing team. You will be responsible for developing and executing digital marketing campaigns across various channels to drive brand awareness and customer acquisition. The role involves content creation, social media management, email marketing, and performance analysis. You will work closely with the sales team and external partners to achieve our growth objectives.',
    location: 'London, UK',
    type: 'Part-Time',
    posted: '5 days ago',
    requirements: [
      '2+ years of digital marketing experience',
      'Strong understanding of social media platforms',
      'Experience with email marketing tools (Mailchimp, HubSpot)',
      'Knowledge of SEO and content marketing',
      'Proficiency in analytics tools (Google Analytics, Facebook Insights)',
      'Creative writing and content creation skills',
      "Bachelor's degree in Marketing or related field",
    ],
    benefits: [
      'Flexible part-time schedule',
      'Competitive hourly rate',
      'Professional development opportunities',
      'Creative and collaborative work environment',
      'Access to marketing tools and resources',
      'Performance-based bonuses',
    ],
  },
  {
    id: '5',
    title: 'DevOps Engineer',
    company: 'CloudTech Solutions',
    description:
      'Seeking an experienced DevOps engineer to manage our cloud infrastructure and implement CI/CD pipelines.',
    fullDescription:
      'CloudTech Solutions is looking for a skilled DevOps Engineer to join our infrastructure team. You will be responsible for managing and optimizing our cloud infrastructure, implementing CI/CD pipelines, and ensuring the reliability and scalability of our systems. The role involves working with various cloud platforms, automation tools, and monitoring systems to support our development and production environments.',
    location: 'Berlin, Germany',
    type: 'Contract',
    posted: '1 day ago',
    requirements: [
      '3+ years of DevOps or infrastructure experience',
      'Strong knowledge of cloud platforms (AWS, Azure, GCP)',
      'Experience with containerization (Docker, Kubernetes)',
      'Proficiency in Infrastructure as Code (Terraform, CloudFormation)',
      'Knowledge of CI/CD tools (Jenkins, GitLab CI, GitHub Actions)',
      'Understanding of monitoring and logging tools',
      'Scripting skills (Bash, Python, PowerShell)',
    ],
    benefits: [
      'Competitive contract rate',
      'Flexible working arrangements',
      'Opportunity to work with cutting-edge technologies',
      'Collaborative international team',
      'Professional development support',
      'Potential for contract extension or permanent role',
    ],
  },
];
